apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-4xx-error-page
data:
  404.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>404 Not Found</title>
    </head>
    <body>
      <h1>404 Not Found</h1>
      <p>Sorry, the page you are looking for does not exist.</p>
    </body>
    </html>
