
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-errors-config
data:
  nginx.conf: |
    server {
        listen       80;
        server_name  localhost;

        error_page 404 /404.html;
        error_page 500 /500.html;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location = /404.html {
            internal;
            root /usr/share/nginx/html;
        }

        location = /500.html {
            internal;
            root /usr/share/nginx/html;
        }
    }
